env:
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/error
  - plugin:import/warnings
  - plugin:import/typescript
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - eslint-plugin-import-helpers
  - import
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - single
  semi:
    - error
    - always
  import/resolver:
    - node:
      - extensions: [".js", ".ts"]
  import-helpers/order-imports:
    - warn
    - newLinesBetween: always
      groups:
        - module
        - /^~shared/
        - /^~docs/
        - /^~modules/
        - /^~/
        - - parent
          - sibling
          - index
      alphabetize:
        order: asc
        ignoreCase: true